version: "3.8"

services:
  backend:
    build: ./backend
    container_name: documind-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - elasticsearch
    networks:
      - documind-net

  frontend:
    build: ./frontend
    container_name: documind-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - documind-net

  elasticsearch:
    image: elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ports:
      - "9200:9200"
    networks:
      - documind-net

networks:
  documind-net:
    driver: bridge
